import { Geist, Geist_Mono, Outfit, Ovo } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import "devicon/devicon.min.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit", // ✅ Added variable
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"],
});

const ovo = Ovo({
  variable: "--font-ovo", // ✅ Added variable
  weight: ["400"],
});

export const metadata = {
  title: "Rahul Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} ${ovo.variable} antialiased`}
      >
        <Header />
        <StairTransition/>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
